services:
  db:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  scraper:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
      - ./dumps:/app/dumps
      - ./logs/scraper:/app/logs
    working_dir: /app
    entrypoint: |
      /bin/sh -c '
      echo "$SCRAPER_CRON_TIME /usr/local/bin/python /app/main.py >> /app/logs/cron.log 2>&1" | crontab -
      cron -f
      '

volumes:
  db_data: